### PR TITLE
chore: Update `PermissionUtils` bits 

### PR DESCRIPTION
**Pull request by Lulalaby**
Renamed useSlashCommands to useApllicationCommands
Renamed use(Private|Public)Threads to create(Private|Public)Threads
Added useExternalStickers
Added sendMessagesInThreads

### CODE REVIEW

**Comment by bryceroethel** [comment]
Some of the changes are unnecessary breaking changes.

**Comment by jpbberry** [comment]
~~Where are the 2 added bits you said you did?~~

I’m blind sorry

**Comment by jpbberry** [comment]
As br said please revoke the breaking changes, you can either leave them or create duplicates and deprecate the old ones

**Comment by Lulalaby** [comment]
@BR88C @jpbberry done ❤️

**Pull request merged**
